apiVersion: v1
kind: Namespace
metadata:
  name: pod-crash-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-crash-injector
  namespace: pod-crash-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-crash-injector
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-crash-injector
subjects:
- kind: ServiceAccount
  name: pod-crash-injector
  namespace: pod-crash-injector
roleRef:
  kind: ClusterRole
  name: pod-crash-injector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-crash-injector
  namespace: pod-crash-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-crash-injector
  template:
    metadata:
      labels:
        app: pod-crash-injector
    spec:
      serviceAccountName: pod-crash-injector
      containers:
      - name: webhook
        image: pod-crash-injector:latest
        imagePullPolicy: IfNotPresent
        args:
        - --port=8443
        - --tlsCertFile=/etc/webhook/certs/tls.crt
        - --tlsKeyFile=/etc/webhook/certs/tls.key
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: pod-crash-injector
  namespace: pod-crash-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: pod-crash-injector
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-crash-injector
webhooks:
- name: pod-crash-injector.default.svc.cluster.local
  clientConfig:
    service:
      name: pod-crash-injector
      namespace: pod-crash-injector
      path: "/mutate"
      port: 443
    caBundle: ${CA_BUNDLE}
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations: ["CREATE", "UPDATE"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5 